blog/urls.py
from django.urls import path
from . import views

app_name="post"
urlpatterns = [
    path('',views.index,name='starting-page'),
    path('posts',views.posts,name='posts-page'),
    path('posts/<slug:slug>',views.singlepost,name='post-detail-page'),
]

blog_django_example/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'))
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from datetime import date

all_posts =[
    {
        "slug":"learning-django",
        "title":"django course",
        "author":"ali pourfereydoon",
        "image":"python.png",
        "date":date(2025, 5,5),
        "short_description":"this is django course in rctnetwork",
        "content":"ali pourfereydoon is a programer"
    },
        {
        "slug":"learning-python",
        "title":"python course",
        "author":"ali pourfereydoon2",
        "image":"django.png",
        "date":date(2025,11,14),
        "short_description":"this is python course in rctnetwork",
        "content":"ali pourfereydoon is a programer"
    },
    {
        "slug":"learning-java",
        "title":"java course",
        "author":"ali pourfereydoon2",
        "image":"django.png",
        "date":date(2025,11,16),
        "short_description":"this is java course in rctnetwork",
        "content":"ali pourfereydoon is a programer"
    }
]

def get_date(post):
    return post['date']


def index(request):
    sorted_post= sorted(all_posts , key=get_date)
    lateste_post = sorted_post[-2:]
    return render(request,'blog/index.html',{"post":lateste_post})

def posts(request):
    all_posts_detail = all_posts
    return render(request,'blog/all-posts.html',context={'all_posts':all_posts_detail}) 

def singlepost(request,slug):
    post = next(post for post in all_posts if post['slug']==slug)
    return render(request,'blog/post_detail.html',context={'post':post})       

blog/templates/blog/all-posts.html
{% extends "base.html" %}
{% load static %}
{% block title %}my blog{% endblock title %}

{% block header_reference %}
<link rel="stylesheet" href="{% static 'blog/index.css' %}">
<link rel="stylesheet" href="{% static 'blog/all-posts.css' %}">
{% endblock header_reference %}

{% block content %}
<section id="all-posts">
    <h2>This is all posts</h2>
    <ul>
        {% for item in all_posts  %}
        {% include "blog/includes/posts.html" %}
        {% endfor %}
        
    </ul>
</section>
{% endblock %}

blog/templates/blog/includes/posts.html
{% load static %}
<li>
    <article class="post">
        <a href="{% url "post:post-detail-page" item.slug %}">
            <img src="{% static 'blog/images/'|add:item.image %}" alt="learning django">
            <div class="post__content">
                <h3>{{item.title}}</h3>
                <p>
                    {{item.short_description}}
                </p>
            </div>
        </a>
    </article>
</li>

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block header_reference %}
    <link rel="stylesheet" href="{% static 'blog/index.css' %}">
{% endblock %}


{% block title %}
    My Blog
{% endblock %}

{% block content %}
    <section id="welcome">
        <header>
            <img src="{% static 'blog/images/master.jpg' %}" alt="Toplearn - Author Of This blog">
            <h2>Hi , I am a web designner</h2>
        </header>
        <p>Hi, My name is Ali, Im a web developer</p>
    </section>

    <section id="latest-posts">
        <h2>Latest Posts</h2>
        <ul>
            {% for item in post  %}
            {% include "blog/includes/posts.html" %}
            {% endfor %}

        </ul>
    </section>

    <section id="about">
        <h2>What I Do</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid dicta, eius eos eum eveniet
            perspiciatis quod soluta veritatis? Alias atque ducimus facere odit pariatur! Alias, aspernatur consequuntur
            deleniti est fugit officiis porro quia saepe tenetur, veniam veritatis voluptatem voluptatum?
        </p>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus ad adipisci architecto atque autem
            corporis deleniti deserunt enim eum fugiat hic laborum nam, natus nisi officia optio porro praesentium
            provident qui quia repellat repellendus repudiandae saepe similique sit tenetur unde voluptatem. Distinctio
            doloremque excepturi fugit harum iste quam sequi veritatis. Aliquam est labore laboriosam magnam maxime quos
            unde voluptate voluptatem!
        </p>
    </section>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{post.title}}{% endblock title %}
{% block header_reference %}
<link rel="stylesheet" href="{% static 'blog/index.css' %}">
<link rel="stylesheet" href="{% static 'blog/post-detail.css' %}">
{% endblock header_reference %}
{% block content %}
<section id="summery">
    <h2>{{post.title}}</h2>
    <article>
<img src="{% static 'blog/images/'|add:post.image %}" alt="">
<address>by {{post.author}}</address>
<div>
    laste updated on
    <time datetime="">{{post.date}}</time>
</div>
    </article>
</section>
<main>
{{post.content}}
</main>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'app.css' %}">
    {% block header_reference %}{% endblock %}
</head>
<body>
<header id="main-navigation">
    <h1><a href="{% url "post:starting-page" %}">individual Blog</a></h1>
    <nav>
        <a href="{% url "post:posts-page" %}">All Posts</a>
    </nav>
</header>
{% block content %}{% endblock %}
{% block footer_references %}{% endblock %}
</body>
</html>